---

- name: install the latest yum version
  yum:
    name: yum
    state: latest

- name: install packages
  yum:
    name: ["pygpgme", "yum-utils", "yum-cron"]
    state: present

- name: configure yum-cron
  template:
    src: templates/yum-cron.conf.j2
    dest: /etc/yum/yum-cron.conf
    mode: 0644
    owner: root
    group: root
  notify:
    - restart yum-cron

- name: start yum-cron
  service:
    name: yum-cron
    state: started
    enabled: yes
